# Travis CI build file for Kitura sample app.
# Kitura runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "nv1kMHlea4PuOu6YH20+Cay5bTcKLirkJFgSXo+2/lP24wx6nKtz4eUS9r1sZ8XlJCyNuQ7XjH7jDQwQpUtfTXkD27XrR1KrlOmLphxfzj8+T9meTwM/Q3Zb8dI7EfAWyqs4Z8iLzFkAviWAIPy8vrk6baN7AwjOHUgnya+3RxBEAg7xsbocwgPilJ0HIB+VhWIIhzrlGNuBj6BQ/D+VyTQTbTZzxYHkZEsPjEvGgAQamGBF6sw6/G11r+bCxilG9r7TVS/jV96vTzzXGJ2hzv3uixTR9nylaxhQYybZQ96JTt1YN1TBF+iSxfx/gjFKvCPMxWvhPEkTCs7zkWThohGpKcy2nRo332zHZ5Ti61jWL0sPUMSU6q5BlBE3flNiqRzaF8Jc1wthxsESEX8rNfmx92Eb2Tet3LjU/VP21lR9WEIGo934np1yrSpaPYweBdNyg1pPzSJeUdSjXHG/4lEEnqQ0TEttdxfaXfPFWQ+qEZUvSsR20gwI3xQA8rFsPZDa39gEBVgLAj+mzKVK3ExfWVTmdsSOqL45MDsnvracZUetMuAKt3ClrGPDCe2whoXWVcX9/7AwUfXbE1YhkpMstAFOsuAyaOYIsfw/fUset1tGv8vjJM6+/cWRueDsTKxT4RkCIW2lQEu1qAJPeuXYXTnNROLAISlnXmGWKvk="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0-DEVELOPMENT-SNAPSHOT-2017-06-25-a
    - os: osx
      osx_image: xcode8.3
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
